names = input("First and last Name: ")
print()
name = input("Last name: ")
print()
citizen = input("Citizen: ")
print()
Profession = input("Profession: ")
print()
EmailAddress = input("EmailAddress: ")
print()
phone = input("Phone: ")
print()
city = input("City:")
print()
Address = input("Address: ")
print()